Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,36 +1,85 @@
-# This is a basic workflow to help you get started with Actions
+# main.yml
 
-name: CI
+# Workflow's name
+name: Build Electron App For Win/Mac
 
-# Controls when the action will run. 
+# Workflow's trigger
 on:
-  # Triggers the workflow on push or pull request events but only for the main branch
   push:
-    branches: [ main ]
-  pull_request:
-    branches: [ main ]
+    tags:
+      - 'v*.*.*'
 
-  # Allows you to run this workflow manually from the Actions tab
-  workflow_dispatch:
-
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
+# Workflow's jobs
 jobs:
-  # This workflow contains a single job called "build"
-  build:
-    # The type of runner that the job will run on
-    runs-on: ubuntu-latest
+  # job's id
+  release:
+    # job's name
+    name: build and release electron app
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
+    # the type of machine to run the job on
+    runs-on: ${{ matrix.os }}
+
+    # create a build matrix for jobs
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [windows-2019, macos-10.15, ubuntu-18.04]
+
+    # create steps
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v2
+      # step1: check out repository
+      - name: Check out git repository
+        uses: actions/checkout@v2
 
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
+      # step2: install node env
+      - name: Install Node.js
+        uses: actions/setup-node@v2-beta
 
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
+      # step3: npm install
+      - name: npm install
         run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+          npm install
+      # step4: build app for mac/win
+      - name: build windows app
+        if: matrix.os == 'windows-2019'
+        run: |
+          npm run build
+      - name: build mac app
+        if: matrix.os == 'macos-10.15'
+        run: |
+          npm run build
+      - name: build Ubuntu app
+        if: matrix.os == 'ubuntu-18.04'
+        run: |
+          npm run build
+      # step5: cleanup artifacts in dist_electron
+      - name: cleanup artifacts for windows
+        if: matrix.os == 'windows-2019'
+        run: |
+          mkdir artifacts
+          mv release/*.exe artifacts || true
+      - name: cleanup artifacts for macosZ
+        if: matrix.os == 'macos-10.15'
+        run: |
+          mkdir artifacts
+          mv release/*.dmg artifacts || true
+      - name: cleanup artifacts for Ubuntu
+        if: matrix.os == 'ubuntu-18.04'
+        run: |
+          mkdir artifacts
+          mv release/*.dmg artifacts || true
+      # step6: upload artifacts
+      - name: upload artifacts
+        uses: actions/upload-artifact@v2
+        with:
+          name: ${{ matrix.os }}
+          path: artifacts
+
+      # step7: create release
+      - name: release
+        uses: softprops/action-gh-release@v1
+        if: startsWith(github.ref, 'refs/tags/')
+        with:
+          files: 'artifacts/**'
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
